# Header
menu:
  首页: /
  产品: /gallery
  解决方案: /stories
  文章: /archives
  关于: /about

# Content
excerpt_link: 阅读全文

# Toc
toc: true

# MIIT ICP/IP/DOMAIN
beian: 
  enable: true
  number: 粤ICP备2021026121号
  url: https://beian.miit.gov.cn/

# Miscellaneous
favicon: /favicon.ico
webclip: /images/webclip
brand:   /images/brand.png

# Jumbotron video & Hero image
## Jumbotron video
video: 
  overlay: false
  path: /images/
## Hero image
hero: 
  image: /images/banner.jpg
## keen-slider
keen_slider: 
  enable: false

# Slogan
slogan: 
  primary: 
  secondary: 
  archives: 汇聚热点话题 打造创新思路
  pages: 运维更智能 部署更方便 应用更便捷
  posts: 实践见真知既是最好的解释


